// The frozen schema-version-1 bundle. src/__tests__/fixtures/feedback-v1.md
// is real text committed once, NOT regenerated by the exporter at test time
// — so it pins both halves of src/bundle/v1.ts independently of each other:
//
//   read:  decodeFeedbackMarkdown(fixture) must produce exactly the items
//          written out by hand below (a v1 bundle already on someone's disk
//          must keep importing after any later format change);
//   write: buildFeedbackMarkdown(those items) must reproduce the fixture
//          byte-for-byte for as long as SCHEMA_VERSION is 1.
//
// When the format is revised: bump SCHEMA_VERSION, add bundle/v2.ts and a
// feedback-v2.md fixture, and change the WRITE half of this file to go
// through v1's writer directly. The READ half must never need to change.
//
// The fixture deliberately covers: two URLs with the section order driven
// by first item id (not insertion order); a multi-paragraph note; an empty
// note; a title and area text containing ": " (which js-yaml quotes); a
// truncated primary target with the visible "...[truncated]" marker and the
// contained_elements_truncated flag; classes/attrs/id/text on contained
// elements; a fractional selection rect and dpr; and js-yaml's quoting of
// the `y` key (`'y':`), which bare would read as a YAML 1.1 boolean.

import * as fs from 'fs';
import * as path from 'path';
import { buildFeedbackMarkdown, decodeFeedbackMarkdown, DecodedBundleItem, parseSchemaVersion } from '../bundle';
import { buildFeedbackMarkdown as buildV1, SCHEMA_VERSION_V1 } from '../bundle/v1';

const FIXTURE_PATH = path.join(__dirname, 'fixtures', 'feedback-v1.md');
const fixture = fs.readFileSync(FIXTURE_PATH, 'utf-8');

const PRICING = 'https://example.com/pricing';
const DOCS = 'https://example.com/docs/getting-started';

/** The items the fixture encodes, written out by hand. */
const ITEM_1: DecodedBundleItem = {
  id: 1,
  pageUrl: 'https://www.example.com/pricing?plan=team',
  normalisedUrl: PRICING,
  note: 'the "start trial" cta is misaligned on mobile',
  createdAt: '2026-09-20T10:15:30.000Z',
  selectionRect: { x: 412, y: 1188, width: 267, height: 100 },
  viewport: { width: 1280, height: 720 },
  dpr: 2,
  context: {
    primaryTarget: {
      cssSelector: 'section.plans > div:nth-of-type(2) > a.btn',
      xpath: '/html/body/main/section[2]/div[2]/a',
      outerHtmlSnippet:
        '<a class="btn btn-primary css-1k2j3h" href="/signup?plan=team" data-track="cta-team">start trial</a>',
      truncated: false,
    },
    containedElements: [
      {
        tag: 'a',
        classes: { semantic: ['btn', 'btn-primary'], generated: ['css-1k2j3h'] },
        attrs: { href: '/signup?plan=team', 'data-track': 'cta-team' },
        text: 'start trial',
      },
      { tag: 'span', id: 'price-team', text: '$12 / seat' },
    ],
    areaText: 'team $12 / seat start trial',
    pageMeta: {
      url: 'https://www.example.com/pricing?plan=team',
      normalisedUrl: PRICING,
      title: 'pricing — example',
      viewport: { width: 1280, height: 720 },
      dpr: 2,
      selectionRect: { x: 412, y: 1188, width: 267, height: 100 },
      capturedAt: '2026-09-20T10:15:30.000Z',
    },
  },
};

const ITEM_2: DecodedBundleItem = {
  id: 2,
  pageUrl: 'https://example.com/docs/getting-started#install',
  normalisedUrl: DOCS,
  note: '',
  createdAt: '2026-09-20T10:16:02.000Z',
  selectionRect: { x: 0, y: 0, width: 640, height: 48 },
  viewport: { width: 1280, height: 720 },
  dpr: 1,
  context: {
    primaryTarget: {
      cssSelector: 'h1',
      xpath: '/html/body/article/h1',
      outerHtmlSnippet: '<h1>docs: getting started</h1>',
      truncated: false,
    },
    containedElements: [],
    areaText: 'docs: getting started',
    pageMeta: {
      url: 'https://example.com/docs/getting-started#install',
      normalisedUrl: DOCS,
      title: 'docs: getting started',
      viewport: { width: 1280, height: 720 },
      dpr: 1,
      selectionRect: { x: 0, y: 0, width: 640, height: 48 },
      capturedAt: '2026-09-20T10:16:02.000Z',
    },
  },
};

const ITEM_3: DecodedBundleItem = {
  id: 3,
  pageUrl: 'https://www.example.com/pricing',
  normalisedUrl: PRICING,
  note: 'the comparison table overflows at 1024px\n\nsecond paragraph: the sticky header covers row one when you scroll',
  createdAt: '2026-09-20T10:17:45.000Z',
  selectionRect: { x: 40.5, y: 2200, width: 1200, height: 900 },
  viewport: { width: 1280, height: 720 },
  dpr: 1.5,
  context: {
    primaryTarget: {
      cssSelector: 'table.compare',
      xpath: '/html/body/main/table',
      outerHtmlSnippet:
        '<table class="compare"><thead><tr><th>feature</th><th>free</th><th>team</th>...[truncated]',
      truncated: true,
    },
    containedElements: [
      { tag: 'th', text: 'feature' },
      { tag: 'th', text: 'free' },
      { tag: 'th', text: 'team' },
    ],
    areaText: 'feature free team unlimited boards 3 unlimited',
    pageMeta: {
      url: 'https://www.example.com/pricing',
      normalisedUrl: PRICING,
      title: 'pricing — example',
      viewport: { width: 1280, height: 720 },
      dpr: 1.5,
      selectionRect: { x: 40.5, y: 2200, width: 1200, height: 900 },
      capturedAt: '2026-09-20T10:17:45.000Z',
    },
    containedElementsTruncated: true,
  },
};

function withHandles(item: DecodedBundleItem) {
  return { ...item, screenshotKey: `key-${item.id}`, thumbnailDataUrl: `data:image/jpeg;base64,T${item.id}` };
}

describe('frozen v1 bundle — read', () => {
  test('the fixture declares schema version 1', () => {
    expect(parseSchemaVersion(fixture)).toBe(1);
    expect(fixture.startsWith('<!-- annotator-schema-version: 1 -->\n')).toBe(true);
  });

  test('decodes to exactly the hand-written items, in document order', () => {
    const decoded = decodeFeedbackMarkdown(fixture);
    expect(decoded.version).toBe(1);
    expect(decoded.versionWarning).toBe(false);
    expect(decoded.items).toEqual([ITEM_1, ITEM_3, ITEM_2]);
  });

  test('a decoded item carries no storage handle', () => {
    for (const item of decodeFeedbackMarkdown(fixture).items) {
      expect(item).not.toHaveProperty('screenshotKey');
      expect(item).not.toHaveProperty('thumbnailDataUrl');
    }
  });
});

describe('frozen v1 bundle — write', () => {
  const pages = {
    // Insertion order is deliberately NOT the fixture's section order.
    [DOCS]: [withHandles(ITEM_2)],
    [PRICING]: [withHandles(ITEM_3), withHandles(ITEM_1)],
  };

  test('the v1 writer reproduces the fixture byte-for-byte', () => {
    expect(buildV1(pages)).toBe(fixture);
  });

  test('the current-version writer is still the v1 writer', () => {
    expect(SCHEMA_VERSION_V1).toBe(1);
    expect(buildFeedbackMarkdown(pages)).toBe(fixture);
  });
});
