// The frozen format-version-2 bundle (design spec §AC).
// src/__tests__/fixtures/feedback-v2.md is real text committed once, NOT
// regenerated by the exporter at test time — so it pins both halves of
// src/bundle/v2.ts independently of each other:
//
//   read:  decodeFeedbackMarkdown(fixture) must rebuild exactly the items
//          written out by hand below (minus the drawing, which travels only
//          as pixels in the PNG — §AB);
//   write: buildFeedbackMarkdown(those items, HEADER) must reproduce the
//          fixture byte-for-byte for as long as FORMAT_VERSION is 2.
//
// The fixture deliberately covers: two pages, in first-capture order (not
// insertion order); two notes on one page with different full urls; a note
// with quotes; a multi-paragraph note; an empty note, shown as "(none)"; a
// note with a drawing (the alt-text suffix); an html snippet capture had
// already cut (its "...[truncated]" marker becomes a single ellipsis in the
// file, and `text` is read up to the cut); an entity in the html (`text`
// decodes it); a contained-element list capture had cut (no flag for it in
// the file);
// classes/attrs/id/text on contained elements; a fractional selection rect
// and dpr; and the header's local time with a negative utc offset.

import * as fs from 'fs';
import * as path from 'path';
import {
  buildFeedbackMarkdown,
  decodeFeedbackMarkdown,
  DecodedBundleItem,
  ExportHeader,
  FORMAT_VERSION,
  parseFormatVersion,
} from '../bundle';
import type { Drawing, FeedbackItem } from '../types';

const FIXTURE_PATH = path.join(__dirname, 'fixtures', 'feedback-v2.md');
const fixture = fs.readFileSync(FIXTURE_PATH, 'utf-8');

const PRICING = 'https://example.com/pricing';
const DOCS = 'https://example.com/docs/getting-started';

/** 21:40 at utc-05:00 on 2026-09-21 — the spec's own example line. */
const HEADER: ExportHeader = {
  extensionVersion: '1.1.0',
  website: 'example.com',
  exportedAt: new Date('2026-09-22T02:40:00.000Z'),
  utcOffsetMinutes: -300,
};

const DRAWING: Drawing = {
  width: 267,
  height: 100,
  strokes: [{ color: '#E5484D', points: [[12, 80], [250, 84]] }],
};

/** The items the fixture encodes, written out by hand. */
const ITEM_1: DecodedBundleItem = {
  id: 1,
  pageUrl: 'https://www.example.com/pricing?plan=team',
  normalisedUrl: PRICING,
  note: 'the "start trial" cta is misaligned on mobile',
  createdAt: '2026-09-20T10:15:30.000Z',
  selectionRect: { x: 412, y: 1188, width: 267, height: 100 },
  viewport: { width: 1280, height: 720 },
  dpr: 2,
  context: {
    primaryTarget: {
      cssSelector: 'section.plans > div:nth-of-type(2) > a.btn',
      xpath: '/html/body/main/section[2]/div[2]/a',
      outerHtmlSnippet:
        '<a class="btn btn-primary css-1k2j3h" href="/signup?plan=team" data-track="cta-team">start trial</a>',
      truncated: false,
    },
    containedElements: [
      {
        tag: 'a',
        classes: { semantic: ['btn', 'btn-primary'], generated: ['css-1k2j3h'] },
        attrs: { href: '/signup?plan=team', 'data-track': 'cta-team' },
        text: 'start trial',
      },
      { tag: 'span', id: 'price-team', text: '$12 / seat' },
    ],
    areaText: 'team $12 / seat start trial',
    pageMeta: {
      url: 'https://www.example.com/pricing?plan=team',
      normalisedUrl: PRICING,
      title: 'pricing — example',
      viewport: { width: 1280, height: 720 },
      dpr: 2,
      selectionRect: { x: 412, y: 1188, width: 267, height: 100 },
      capturedAt: '2026-09-20T10:15:30.000Z',
    },
  },
};

const ITEM_2: DecodedBundleItem = {
  id: 2,
  pageUrl: 'https://example.com/docs/getting-started#install',
  normalisedUrl: DOCS,
  note: '',
  createdAt: '2026-09-20T10:16:02.000Z',
  selectionRect: { x: 0, y: 0, width: 640, height: 48 },
  viewport: { width: 1280, height: 720 },
  dpr: 1,
  context: {
    primaryTarget: {
      cssSelector: 'h1',
      xpath: '/html/body/article/h1',
      outerHtmlSnippet: '<h1>docs &amp; setup: getting started</h1>',
      truncated: false,
    },
    containedElements: [],
    areaText: 'docs & setup: getting started',
    pageMeta: {
      url: 'https://example.com/docs/getting-started#install',
      normalisedUrl: DOCS,
      title: 'docs: getting started',
      viewport: { width: 1280, height: 720 },
      dpr: 1,
      selectionRect: { x: 0, y: 0, width: 640, height: 48 },
      capturedAt: '2026-09-20T10:16:02.000Z',
    },
  },
};

const ITEM_3: DecodedBundleItem = {
  id: 3,
  pageUrl: 'https://www.example.com/pricing',
  normalisedUrl: PRICING,
  note: 'the comparison table overflows at 1024px\n\nsecond paragraph: the sticky header covers row one when you scroll',
  createdAt: '2026-09-20T10:17:45.000Z',
  selectionRect: { x: 40.5, y: 2200, width: 1200, height: 900.25 },
  viewport: { width: 1280, height: 720 },
  dpr: 1.5,
  context: {
    primaryTarget: {
      cssSelector: 'table.compare',
      xpath: '/html/body/main/table',
      outerHtmlSnippet:
        '<table class="compare"><thead><tr><th>feature</th><th>free</th><th class="hi...[truncated]',
      truncated: true,
    },
    containedElements: [
      { tag: 'th', text: 'feature' },
      { tag: 'th', text: 'free' },
      { tag: 'th', text: 'team' },
    ],
    areaText: 'feature free team unlimited boards 3 unlimited',
    pageMeta: {
      url: 'https://www.example.com/pricing',
      normalisedUrl: PRICING,
      title: 'pricing — example',
      viewport: { width: 1280, height: 720 },
      dpr: 1.5,
      selectionRect: { x: 40.5, y: 2200, width: 1200, height: 900.25 },
      capturedAt: '2026-09-20T10:17:45.000Z',
    },
    containedElementsTruncated: true,
  },
};

/** ITEM_3 as the reader gives it back. The file is the record, so what the
 *  writer changed comes back changed: capture's cut marker is the one
 *  ellipsis now, and the file carries no truncation flag for the list (§AC). */
const ITEM_3_READ: DecodedBundleItem = (() => {
  const { containedElementsTruncated: _dropped, ...context } = ITEM_3.context;
  return {
    ...ITEM_3,
    context: {
      ...context,
      primaryTarget: {
        ...ITEM_3.context.primaryTarget,
        outerHtmlSnippet:
          '<table class="compare"><thead><tr><th>feature</th><th>free</th><th class="hi\u2026',
        truncated: true,
      },
    },
  };
})();

function stored(item: DecodedBundleItem, drawing?: Drawing): FeedbackItem {
  return {
    ...item,
    screenshotKey: `key-${item.id}`,
    thumbnailDataUrl: `data:image/jpeg;base64,T${item.id}`,
    ...(drawing ? { drawing } : {}),
  };
}

/** The stored pages behind the fixture. Insertion order is deliberately NOT
 *  the fixture's page or note order. */
const FIXTURE_PAGES: Record<string, FeedbackItem[]> = {
  [DOCS]: [stored(ITEM_2)],
  [PRICING]: [stored(ITEM_3), stored(ITEM_1, DRAWING)],
};

describe('frozen v2 bundle — read', () => {
  test('line 1 is the format stamp', () => {
    expect(FORMAT_VERSION).toBe(2);
    expect(fixture.startsWith('<!-- salamander-feedback-format: 2 -->\n')).toBe(true);
    expect(parseFormatVersion(fixture)).toBe(2);
  });

  test('decodes to exactly the hand-written items, in document order, without the drawing', () => {
    const decoded = decodeFeedbackMarkdown(fixture);
    expect(decoded.version).toBe(2);
    expect(decoded.items).toEqual([ITEM_1, ITEM_3_READ, ITEM_2]);
  });

  test('a decoded item carries no storage handle and no drawing', () => {
    for (const item of decodeFeedbackMarkdown(fixture).items) {
      expect(item).not.toHaveProperty('screenshotKey');
      expect(item).not.toHaveProperty('thumbnailDataUrl');
      expect(item).not.toHaveProperty('drawing');
    }
  });

  test('the visible note line is ignored: editing it changes nothing that is read', () => {
    const edited = fixture.replace(
      '**note:** the "start trial" cta is misaligned on mobile',
      '**note:** someone rewrote this line by hand',
    );
    expect(edited).not.toBe(fixture);
    expect(decodeFeedbackMarkdown(edited).items[0].note).toBe(ITEM_1.note);
  });

  test('a copy saved with windows line endings and a byte-order mark still reads', () => {
    const crlf = `\uFEFF${fixture.replace(/\n/g, '\r\n')}`;
    expect(decodeFeedbackMarkdown(crlf).items).toEqual([ITEM_1, ITEM_3_READ, ITEM_2]);
  });
});

describe('frozen v2 bundle — write', () => {
  test('the writer reproduces the fixture byte-for-byte', () => {
    expect(buildFeedbackMarkdown(FIXTURE_PAGES, HEADER)).toBe(fixture);
  });

  test('without the drawing only the alt text changes (the drawing is pixels, not data — §AB)', () => {
    const plain = { ...FIXTURE_PAGES, [PRICING]: [stored(ITEM_3), stored(ITEM_1)] };
    expect(buildFeedbackMarkdown(plain, HEADER)).toBe(
      fixture.replace('![feedback 1 — marked up by the reviewer]', '![feedback 1]'),
    );
    expect(fixture).not.toMatch(/strokes|#E5484D/);
  });

  test('every fixed label and piece of fixed text is lowercase', () => {
    // Everything outside the json blocks and the note text is the writer's
    // own; user content in this fixture is lowercase too, so the whole
    // non-json text must be.
    const outsideJson = fixture.replace(/```json\n[\s\S]*?\n```/g, '');
    expect(outsideJson).toBe(outsideJson.toLowerCase());
  });
});
